# Generated by Django 6.1.1 on 2026-09-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="building",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="incident",
            name="room",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
