# Generated by Django 6.1.1 on 2026-10-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0002_incident_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(default="reporter", max_length=20),
        ),
    ]
