# Generated by Django 6.1.1 on 2026-10-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentupdate",
            name="new_status",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="incidentupdate",
            name="old_status",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("acknowledged", "Acknowledged"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
